server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**, /myPages/**
        - id: ordermanagement
          uri: http://localhost:8082
          predicates:
            - Path=/ordermgmts/** 
        - id: delivery
          uri: http://localhost:8083
          predicates:
            - Path=/deliveries/** 
        - id: payment
          uri: http://localhost:8086
          predicates:
            - Path=/payments/** 
        - id: settlement
          uri: http://localhost:8085
          predicates:
            - Path=/settlements/**, /mySettlements/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/orders/**, /myPages/**
        - id: ordermanagement
          uri: http://ordermanagement:8080
          predicates:
            - Path=/ordermgmts/** 
        - id: delivery
          uri: http://delivery:8080
          predicates:
            - Path=/deliveries/** 
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/payments/** 
        - id: settlement
          uri: http://localhost:8080
          predicates:
            - Path=/settlements/** , /mySettlements/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
